import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <header className="relative flex items-center px-[5%] py-5">
        <picture className="">
          <source
            srcSet="/images/desktop/image-header.jpg"
            media="(min-width: 376px)"
          />
          <Image
            src={"/images/mobile/image-header.jpg"}
            alt="header"
            width={100}
            height={100}
            className="absolute left-0 top-0 -z-10 h-auto w-full"
          />
        </picture>
        <Image
          src={"/images/logo.svg"}
          width={100}
          height={100}
          alt="logo"
          className=""
        />
        <nav className="Fm:hidden ml-auto">
          <Image
            src={"/images/icon-hamburger.svg"}
            width="24"
            height="18"
            alt="menu"
            className=""
            onClick={() => setIsOpen(!isOpen)}
          />
          {isOpen && (
            <div className="Fm:hidden pt-1- absolute left-0 z-10 mx-[5%] mt-[10%] flex w-[90%] flex-col bg-white p-8 text-center">
              <div className="absolute -top-5 right-0 h-0 w-0 border-b-[50px] border-r-[75px] border-t-[50px] border-white border-b-transparent border-t-transparent"></div>
              {["About", "Services", "Projects"].map((item) => (
                <p
                  key={item}
                  className="font-Fm-barlow text-Fm-Grayish-blue py-6 font-bold tracking-wider"
                >
                  {item}
                </p>
              ))}
              <button className="font-Fm-fraunces bg-Fm-Yellow mb-8 self-center rounded-full px-6 py-4">
                CONTACT
              </button>
            </div>
          )}
        </nav>
        <nav className="Fm:visible Fm:static invisible absolute ml-auto flex gap-8">
          {["About", "Services", "Projects"].map((item) => (
            <p
              key={item}
              className="text-Fm-White font-Fm-barlow py-6 font-bold tracking-wider"
            >
              {item}
            </p>
          ))}
          <button className="font-Fm-fraunces bg-Fm-White hover:text-Fm-White Fm:visible Fm:static invisible absolute rounded-full px-7 py-2 hover:cursor-pointer hover:bg-[#6dcffe]">
            CONTACT
          </button>
        </nav>
      </header>
      <p className="font-Fm-fraunces absolute top-[18%] w-full text-center text-4xl font-black tracking-[0.2em] text-white">
        WE ARE CREATIVES
        <Image
          src={"/images/icon-arrow-down.svg"}
          width="36"
          height="114"
          alt="arrow"
          className={`mx-auto pt-10`}
        />
      </p>
      <section className="relative mt-[126%]">
        <article>
          <picture>
            <source
              srcSet="/images/desktop/image-transform.jpg"
              media="(min-width: 376px)"
            />
            <Image
              src={"/images/mobile/image-transform.jpg"}
              alt={"transform"}
              width={100}
              height={100}
              className="w-full"
            />
          </picture>
          <div>
            <h2>Transform your brand</h2>
            <p>
              We are a full-service creative agency specializing in helping
              brands grow fast. Engage your clients through compelling visuals
              that do most of the marketing for you.
            </p>
            <button>LEARN MORE</button>
          </div>
        </article>
      </section>
      <aside></aside>
      <footer></footer>
    </>
  );
}
